PORTNAME= simple-port-example
CATEGORIES= devel
DISTVERSION= 1.0.0
DISTVERSIONPREFIX= v

MAINTAINER= pat@patmaddox.com

USE_GITHUB= yes
GH_ACCOUNT= patmaddox
GH_PROJECT= simple_port_example

.include <bsd.port.mk>
